# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: swift-actions/setup-swift@v2.1.0
      with:
        swift-version: "5.10.1"
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test --enable-code-coverage
      working-directory: .
    - name: Make Sonar Compatible Code Coverage Report
      run: xcrun llvm-cov show -instr-profile=.build/debug/codecov/default.profdata .build/debug/PCPClientPackageTests.xctest/Contents/MacOS/PCPClientPackageTests > coverage.report
    - name: Upload Coverage
      uses: actions/upload-artifact@v4
      with:
        name: Coverage
        path: coverage.report 
        retention-days: 1
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Download Coverage
        uses: actions/download-artifact@v4
        with:
          name: Coverage
      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.swift.coverage.reportPaths=coverage.report
            -Dsonar.verbose=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
